version: '3.8'

services:
  ai-agents:
    # 使用 Docker Hub 上的映像（請將 kevin950805 替換為您的實際用戶名）
    image: kevin950805/ai-agents:latest
    container_name: ai-agents-app
    ports:
      - "5000:5000"  # 映像內部使用 5000 埠
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
    volumes:
      # 掛載整個應用目錄，讓 Docker 自動管理檔案
      - ./app-data:/app/data
      # 掛載日誌目錄
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-agents-network

networks:
  ai-agents-network:
    driver: bridge
