services:
  ai-agents:
    # 使用 Docker Hub 上的映像（請將 kevin950805 替換為您的實際用戶名）
    image: kevin950805/ai-agents:latest
    container_name: ai-agents-app
    ports:
      - "5000:8000"  # 將本地 5000 埠映射到容器內的 8000 埠
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000  # 容器內使用 8000 埠
      - DEBUG=False
    volumes:
      # 使用 Docker 卷來持久化資料庫，避免檔案掛載問題
      - ai-agents-data:/app
      # 掛載整個資料目錄而不是單一檔案
      - ./data:/app/data
      # 可選：掛載日誌目錄
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-agents-network

networks:
  ai-agents-network:
    driver: bridge

volumes:
  ai-agents-data:
    driver: local
