version: '3.8'

services:
  ai-agents:
    # 使用 Docker Hub 上的映像（請將 kevin950805 替換為您的實際用戶名）
    image: kevin950805/ai-agents:latest
    container_name: ai-agents-app
    ports:
      - "5000:5000"  # 映像內部使用 5000 埠
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
    volumes:
      # 解決方案1: 掛載整個資料目錄而不是單一檔案
      - ./data:/app/data
      # 解決方案2: 或者使用 Docker volume
      # - ai-agents-data:/app/data
      # 可選：掛載日誌目錄
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-agents-network

# 如果使用 Docker volume，取消註解以下部分
# volumes:
#   ai-agents-data:
#     driver: local

networks:
  ai-agents-network:
    driver: bridge
